name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation_ubuntu:
      name: 'Code Validation on ubuntu'
      strategy:
        matrix:
          python-version: ['3.8', '3.9', '3.10.', '3.11', 'pypy3.8']
          tools: ['black', 'bandit', 'pylint', 'flake8']
          include:
            - tools: pytest
              args: -m not integration and not gpu
              python-version: 3.11
            - tools: pytest
              args: -m integration
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3.5.3
        - name: ${{ matrix.tools }}
          uses: microsoft/action-python@0.7.0
          with:
            ${{ matrix.tools }}: true
            python_version: ${{ matrix.python-version }}
            workdir: '.'
            args: ${{ matrix.args }}
          env:
            PCO_USER: ${{ secrets.PCO_USER }}
            PCO_PASSWD: ${{ secrets.PCO_PASSWD }}