name: container

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Container Image
        uses: docker/build-push-action@v5
        with:
          push: false
